### 1. Перевірка зв'язку з сервером (Ping)
GET https://github-release-notifier-2.onrender.com/ping

### 2. Підписка на релізи (Production)
POST https://github-release-notifier-2.onrender.com//api/subscribe
Content-Type: application/json
X-API-Key: super-secret-key-123

{
  "email": "test@example.com",
  "repository": "golang/go"
}

### ---------------------------------------------------------
### ЛОКАЛЬНІ ТЕСТИ (для розробки)
### ---------------------------------------------------------

### Локальний Ping
GET http://localhost:8081/ping

### Локальна підписка
POST http://localhost:8081/api/subscribe
Content-Type: application/json
X-API-Key: super-secret-key-123

{
  "email": "local-test@example.com",
  "repository": "gin-gonic/gin"
}